### This notebook demonstrates the use of padding in NLP.
#### The '_pad_sequences_' class from the *tf.keras.preprocessing.sequence* sub-library is used to pad our data.

In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
pad_sequences??

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

2022-05-26 20:14:59.664335: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-26 20:14:59.664435: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
sentence = [
    'I love my dog',
    'I love my cat.',
    'Do you think my dog is amazing?'
]

In [3]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')

In [4]:
tokenizer.fit_on_texts(sentence)

In [5]:
word_index = tokenizer.word_index

In [7]:
#Generate sequences.
sequence = tokenizer.texts_to_sequences(sentence)

In [8]:
print(sequence)
print(sentence)

[[3, 4, 2, 5], [3, 4, 2, 6], [7, 8, 9, 2, 5, 10, 11]]
['I love my dog', 'I love my cat.', 'Do you think my dog is amazing?']


In [9]:
padded = pad_sequences(sequence)
print(padded)

[[ 0  0  0  3  4  2  5]
 [ 0  0  0  3  4  2  6]
 [ 7  8  9  2  5 10 11]]


In [10]:
post_padded = pad_sequences(sequence, padding='post')
print(post_padded)

[[ 3  4  2  5  0  0  0]
 [ 3  4  2  6  0  0  0]
 [ 7  8  9  2  5 10 11]]


In [11]:
pad_sequences??